import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-prompt-pour-member-token","Access-Control-Allow-Methods":"POST, OPTIONS"};
type MemberAction = "upload_screenshot" | "sign_member_screenshots";
type MemberTokenPayload = { role: string; exp: number };
function jsonResponse(status:number,body:Record<string,unknown>){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
function decodeBase64Url(value:string){const n=value.replace(/-/g,"+").replace(/_/g,"/");const p=n+"=".repeat((4-(n.length%4))%4);return atob(p)}
async function verifyToken(token:string,secret:string):Promise<MemberTokenPayload|null>{const [p,s]=token.split(".");if(!p||!s)return null;const pj=decodeBase64Url(p);const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["verify"]);const sig=Uint8Array.from(decodeBase64Url(s),(c)=>c.charCodeAt(0));const ok=await crypto.subtle.verify("HMAC",key,sig,new TextEncoder().encode(pj));if(!ok)return null;const payload=JSON.parse(pj) as MemberTokenPayload;const now=Math.floor(Date.now()/1000);if(payload.role!=="member"||typeof payload.exp!=="number"||payload.exp<=now)return null;return payload}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return jsonResponse(405,{error:"Method not allowed"});const supabaseUrl=Deno.env.get("SUPABASE_URL");const serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const memberTokenSigningSecret=Deno.env.get("PROMPT_POUR_MEMBER_TOKEN_SECRET")||Deno.env.get("PROMPT_POUR_ADMIN_TOKEN_SECRET");if(!supabaseUrl||!serviceRoleKey||!memberTokenSigningSecret)return jsonResponse(500,{error:"Missing server configuration."});const payload=await req.json().catch(()=>({}));const providedToken=req.headers.get("x-prompt-pour-member-token")||payload.memberToken||"";const tokenPayload=providedToken?await verifyToken(providedToken,memberTokenSigningSecret):null;if(!tokenPayload)return jsonResponse(401,{error:"Unauthorized"});const action=payload.action as MemberAction;const supabase=createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}});
if(action==="upload_screenshot"){const fileName=String(payload.fileName||"screenshot");const contentType=String(payload.contentType||"");const dataUrl=String(payload.dataUrl||"");if(!dataUrl.startsWith("data:"))return jsonResponse(400,{error:"Invalid image payload."});const base64=dataUrl.split(",")[1]||"";const bytes=Uint8Array.from(atob(base64),(c)=>c.charCodeAt(0));const ext=contentType==="image/png"?"png":contentType==="image/webp"?"webp":"jpg";const path=`member-uploads/${crypto.randomUUID()}-${fileName.replace(/[^a-zA-Z0-9_.-]/g,"_")}.${ext}`;const {error}=await supabase.storage.from("prompt-pour-screenshots").upload(path,bytes,{contentType,upsert:false});if(error)return jsonResponse(500,{error:error.message});return jsonResponse(200,{path});}
if(action==="sign_member_screenshots"){const rawPaths=Array.isArray(payload.paths)?payload.paths.filter((v:unknown)=>typeof v==="string") as string[]:[];const paths=[...new Set(rawPaths.map((v)=>v.trim()).filter((v)=>v.startsWith("member-uploads/")&&!/^https?:\/\//i.test(v)))];if(!paths.length)return jsonResponse(200,{signed:{}});const {data,error}=await supabase.storage.from("prompt-pour-screenshots").createSignedUrls(paths,900);if(error)return jsonResponse(500,{error:error.message});const signed=Object.fromEntries(data.map((entry,idx)=>{const signedUrl=entry?.signedUrl||"";const absolute=signedUrl.startsWith("http")?signedUrl:`${supabaseUrl}/storage/v1${signedUrl}`;return [paths[idx],absolute];}));return jsonResponse(200,{signed});}
return jsonResponse(400,{error:"Unsupported action."});});
